(Summary (gene ENSG00000128245) "The gene ENSG00000128245, encoding the protein YWHAH, is located on chromosome 22 and spans from position 31944522 to 31957603.  YWHAH, also known as 14-3-3 eta, functions as a tyrosine/tryptophan monooxygenase activation protein." )

(Summary (gene ENSG00000166913) "The ENSG00000166913 gene, located on chromosome 20, encodes the protein-coding gene YWHAB, also known as 14-3-3 beta/alpha. YWHAB is a protein kinase C inhibitor and participates in tyrosine/tryptophan monooxygenase activation, with various synonyms reflecting its diverse functions." )

(Summary (gene ENSG00000108953) "The gene ENSG00000108953 (YWHAE), located on chromosome 17, encodes the 14-3-3 epsilon protein, a key regulator involved in diverse signaling pathways. This protein, also known by multiple aliases, participates in processes ranging from protein kinase inhibition to mitochondrial import stimulation." )

(Summary (gene ENSG00000170027) "The YWHAG gene (ENSG00000170027), located on chromosome 7, encodes the 14-3-3 gamma protein involved in protein kinase C inhibition and protein phosphatase regulation. This protein, also known as tyrosine 3-monooxygenase/tryptophan 5-monooxygenase activation protein gamma, is associated with developmental and epileptic encephalopathy 56 (DEE56/EIEE56)." )

(Summary (gene ENSG00000134308) "The gene ENSG00000134308, located on chromosome 2, encodes the protein YWHAQ, a 14-3-3 protein involved in signal transduction.  This protein, also known by multiple synonyms, functions as a tyrosine/tryptophan monooxygenase activation protein and is linked to HGNC:12854." )

